In [1]:
from theano.sandbox import cuda
from

In [2]:
%matplotlib inline
import utils; reload(utils)
from utils import *
from __future__ import division, print_function

Using TensorFlow backend.

In [3]:
#path = "data/ml-20m/"
path = "../data/mind_user_answers/workfile.csv"
model_path = "../data/mind_user_answers/model/"
print (os.path.exists(path))
if not os.path.exists(model_path): 
    os.mkdir(model_path)
batch_size=64

True

In [4]:
import pandas as pd
import numpy as np
import scipy
import shlex
## shlex for making comma
from sklearn import preprocessing, cross_validation, neighbors

In [5]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


from sklearn import decomposition
from sklearn import datasets

## Data Preprocess

In [6]:
path = "../data/mind_user_answers/workfile.csv"

In [7]:
ratings = pd.read_csv(path)

In [8]:
ratings

             U9 2015-11-16 20:44:38 2015-11-16.1 20:50:07
0            U9        Q96        N          NaN      NaN
1            U9         Q4        Y          NaN      NaN
2            U9        Q10        N          NaN      NaN
3            U9        Q44        Y          NaN      NaN
4            U9        Q51        N          NaN      NaN
5            U9        Q95        Y          NaN      NaN
6            U9        Q43        N          NaN      NaN
7            U9        Q57        N          NaN      NaN
8            U9        Q67        N          NaN      NaN
9            U9        Q99        Y          NaN      NaN
10           U9        Q78        N          NaN      NaN
11           U9        Q46        N          NaN      NaN
12           U9        Q21        N          NaN      NaN
13           U9        Q52        Y          NaN      NaN
14           U9        Q31        Y          NaN      NaN
15           U9        Q50        Y          NaN      NaN
16           U9        Q48        Y          NaN      NaN
17           U9        Q76        Y          NaN      NaN
18           U9        Q98        N          NaN      NaN
19           U9         Q1        Y          NaN      NaN
20           U9         Q3        N          NaN      NaN
21           U9        Q69        N          NaN      NaN
22           U9        Q86        N          NaN      NaN
23           U9        Q40        N          NaN      NaN
24           U9        Q88        N          NaN      NaN
25           U9        Q45        Y          NaN      NaN
26           U9        Q35        Y          NaN      NaN
27           U9        Q42        N          NaN      NaN
28           U9        Q89        Y          NaN      NaN
29           U9        Q82        Y          NaN      NaN
...         ...        ...      ...          ...      ...
4564361  U54106        Q50        N          NaN      NaN
4564362  U54106        Q37        Y          NaN      NaN
4564363  U54106        Q68        Y          NaN      NaN
4564364  U54106        Q16        Y          NaN      NaN
4564365  U54106        Q45        Y          NaN      NaN
4564366  U54106        Q47        N          NaN      NaN
4564367  U54106        Q19        N          NaN      NaN
4564368  U54106        Q99        N          NaN      NaN
4564369  U54106        Q24        N          NaN      NaN
4564370  U54106        Q53        N          NaN      NaN
4564371  U54106        Q95        N          NaN      NaN
4564372  U54106        Q31        N          NaN      NaN
4564373  U54106        Q96        Y          NaN      NaN
4564374  U54106        Q90        N          NaN      NaN
4564375  U54106        Q85        Y          NaN      NaN
4564376  U54106        Q51        N          NaN      NaN
4564377  U54106        Q56        Y          NaN      NaN
4564378  U54106        Q93        Y          NaN      NaN
4564379  U54106         Q2        N          NaN      NaN
4564380  U54106        Q72        N          NaN      NaN
4564381  U54106        Q57        Y          NaN      NaN
4564382  U54106        Q48        N          NaN      NaN
4564383  U54106        Q92        N          NaN      NaN
4564384  U54106        Q10        N          NaN      NaN
4564385  U54106        Q55        Y          NaN      NaN
4564386  U54106        Q82        N          NaN      NaN
4564387  U54106        Q75        N          NaN      NaN
4564388  U54106        Q40        Y          NaN      NaN
4564389  U54106        Q22        Y          NaN      NaN
4564390  U54106        Q71        Y          NaN      NaN

[4564391 rows x 5 columns]

In [9]:
ratings.columns

Index([u'U9', u'2015-11-16', u'20:44:38', u'2015-11-16.1', u'20:50:07'], dtype='object')

In [10]:
ratings = ratings.drop('2015-11-16.1', axis=1)

In [11]:
ratings = ratings.drop('20:50:07', axis=1)

In [12]:
ratings

             U9 2015-11-16 20:44:38
0            U9        Q96        N
1            U9         Q4        Y
2            U9        Q10        N
3            U9        Q44        Y
4            U9        Q51        N
5            U9        Q95        Y
6            U9        Q43        N
7            U9        Q57        N
8            U9        Q67        N
9            U9        Q99        Y
10           U9        Q78        N
11           U9        Q46        N
12           U9        Q21        N
13           U9        Q52        Y
14           U9        Q31        Y
15           U9        Q50        Y
16           U9        Q48        Y
17           U9        Q76        Y
18           U9        Q98        N
19           U9         Q1        Y
20           U9         Q3        N
21           U9        Q69        N
22           U9        Q86        N
23           U9        Q40        N
24           U9        Q88        N
25           U9        Q45        Y
26           U9        Q35        Y
27           U9        Q42        N
28           U9        Q89        Y
29           U9        Q82        Y
...         ...        ...      ...
4564361  U54106        Q50        N
4564362  U54106        Q37        Y
4564363  U54106        Q68        Y
4564364  U54106        Q16        Y
4564365  U54106        Q45        Y
4564366  U54106        Q47        N
4564367  U54106        Q19        N
4564368  U54106        Q99        N
4564369  U54106        Q24        N
4564370  U54106        Q53        N
4564371  U54106        Q95        N
4564372  U54106        Q31        N
4564373  U54106        Q96        Y
4564374  U54106        Q90        N
4564375  U54106        Q85        Y
4564376  U54106        Q51        N
4564377  U54106        Q56        Y
4564378  U54106        Q93        Y
4564379  U54106         Q2        N
4564380  U54106        Q72        N
4564381  U54106        Q57        Y
4564382  U54106        Q48        N
4564383  U54106        Q92        N
4564384  U54106        Q10        N
4564385  U54106        Q55        Y
4564386  U54106        Q82        N
4564387  U54106        Q75        N
4564388  U54106        Q40        Y
4564389  U54106        Q22        Y
4564390  U54106        Q71        Y

[4564391 rows x 3 columns]

In [13]:
ratings = ratings.rename(index=str, columns={"U9": "Users_ID", "2015-11-16": "Questions", "20:44:38" : "Y_or_N"})

In [14]:
ratings = ratings[(ratings.Y_or_N == 'Y') | (ratings.Y_or_N == 'N')]

In [15]:
ratings

        Users_ID Questions Y_or_N
0             U9       Q96      N
1             U9        Q4      Y
2             U9       Q10      N
3             U9       Q44      Y
4             U9       Q51      N
5             U9       Q95      Y
6             U9       Q43      N
7             U9       Q57      N
8             U9       Q67      N
9             U9       Q99      Y
10            U9       Q78      N
11            U9       Q46      N
12            U9       Q21      N
13            U9       Q52      Y
14            U9       Q31      Y
15            U9       Q50      Y
16            U9       Q48      Y
17            U9       Q76      Y
18            U9       Q98      N
19            U9        Q1      Y
20            U9        Q3      N
21            U9       Q69      N
22            U9       Q86      N
23            U9       Q40      N
24            U9       Q88      N
25            U9       Q45      Y
26            U9       Q35      Y
27            U9       Q42      N
28            U9       Q89      Y
29            U9       Q82      Y
...          ...       ...    ...
4564361   U54106       Q50      N
4564362   U54106       Q37      Y
4564363   U54106       Q68      Y
4564364   U54106       Q16      Y
4564365   U54106       Q45      Y
4564366   U54106       Q47      N
4564367   U54106       Q19      N
4564368   U54106       Q99      N
4564369   U54106       Q24      N
4564370   U54106       Q53      N
4564371   U54106       Q95      N
4564372   U54106       Q31      N
4564373   U54106       Q96      Y
4564374   U54106       Q90      N
4564375   U54106       Q85      Y
4564376   U54106       Q51      N
4564377   U54106       Q56      Y
4564378   U54106       Q93      Y
4564379   U54106        Q2      N
4564380   U54106       Q72      N
4564381   U54106       Q57      Y
4564382   U54106       Q48      N
4564383   U54106       Q92      N
4564384   U54106       Q10      N
4564385   U54106       Q55      Y
4564386   U54106       Q82      N
4564387   U54106       Q75      N
4564388   U54106       Q40      Y
4564389   U54106       Q22      Y
4564390   U54106       Q71      Y

[4519200 rows x 3 columns]

In [16]:
ratings['Users_ID'] = ratings['Users_ID'].str.replace(r'\D+', '').astype('int')

In [17]:
ratings['Questions'] = ratings['Questions'].str.replace(r'\D+', '').astype('int')

In [18]:
ratings['Y_or_N'] = ratings['Y_or_N'].str.replace('N', '0')

In [19]:
ratings['Y_or_N'] = ratings['Y_or_N'].str.replace('Y', '1')

In [20]:
ratings['Y_or_N'] = ratings['Y_or_N'].str.replace(r'\D+', '').astype('int')

In [21]:
ratings

         Users_ID  Questions  Y_or_N
0               9         96       0
1               9          4       1
2               9         10       0
3               9         44       1
4               9         51       0
5               9         95       1
6               9         43       0
7               9         57       0
8               9         67       0
9               9         99       1
10              9         78       0
11              9         46       0
12              9         21       0
13              9         52       1
14              9         31       1
15              9         50       1
16              9         48       1
17              9         76       1
18              9         98       0
19              9          1       1
20              9          3       0
21              9         69       0
22              9         86       0
23              9         40       0
24              9         88       0
25              9         45       1
26              9         35       1
27              9         42       0
28              9         89       1
29              9         82       1
...           ...        ...     ...
4564361     54106         50       0
4564362     54106         37       1
4564363     54106         68       1
4564364     54106         16       1
4564365     54106         45       1
4564366     54106         47       0
4564367     54106         19       0
4564368     54106         99       0
4564369     54106         24       0
4564370     54106         53       0
4564371     54106         95       0
4564372     54106         31       0
4564373     54106         96       1
4564374     54106         90       0
4564375     54106         85       1
4564376     54106         51       0
4564377     54106         56       1
4564378     54106         93       1
4564379     54106          2       0
4564380     54106         72       0
4564381     54106         57       1
4564382     54106         48       0
4564383     54106         92       0
4564384     54106         10       0
4564385     54106         55       1
4564386     54106         82       0
4564387     54106         75       0
4564388     54106         40       1
4564389     54106         22       1
4564390     54106         71       1

[4519200 rows x 3 columns]

ratings = ratings.sort(['Questions','Users_ID'], ascending=[True, True])

# Model 1. Using Latent Factor[also used in Movie Recommendation System]

In [59]:
n_factors = 50

In [60]:
np.random.seed = 42

In [61]:
msk = np.random.rand(len(ratings)) < 0.8
trn = ratings[msk]
val = ratings[~msk]

In [62]:
cross = pd.crosstab(ratings.Users_ID, ratings.Questions, ratings.Y_or_N , aggfunc=np.sum)

In [69]:
n_users = len(cross)
n_questions = len(cross.columns)

In [70]:
len(cross.columns)

100

In [81]:
len(cross)

45192

In [41]:
user_in = Input(shape=(1,), dtype='int64', name='user_in')
u = Embedding(n_users, n_factors, input_length=1, W_regularizer=l2(1e-4))(user_in)

question_in = Input(shape=(1,), dtype='int64', name='movie_in')
m = Embedding(n_questions, n_factors, input_length=1, W_regularizer=l2(1e-4))(question_in)

100

In [85]:
49467 in trn.Users_ID.values

True

In [86]:
x = merge([u, m], mode='dot')
x = Flatten()(x)
model = Model([user_in, question_in], x)
model.compile(Adam(0.001), loss='mse')

In [52]:
model

In [77]:
model.fit([trn.Users_ID, trn.Questions], trn.Y_or_N, batch_size=64, nb_epoch=1, 
          validation_data=([val.Users_ID, val.Questions], val.Y_or_N))

Train on 3615269 samples, validate on 903931 samples
Epoch 1/1

InvalidArgumentError: indices[1,0] = 49467 is not in [0, 45192)
	 [[Node: Gather_2 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_3_W/read, Cast_3)]]

Caused by op u'Gather_2', defined at:
  File "/Users/choelinbeom/anaconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/choelinbeom/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 653, in launch_instance
    app.start()
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-41-a16114f85dd0>", line 2, in <module>
    u = Embedding(n_users, n_factors, input_length=1, W_regularizer=l2(1e-4))(user_in)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/keras/layers/embeddings.py", line 128, in call
    out = K.gather(W, x)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 960, in gather
    return tf.gather(reference, indices)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1359, in gather
    validate_indices=validate_indices, name=name)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/choelinbeom/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): indices[1,0] = 49467 is not in [0, 45192)
	 [[Node: Gather_2 = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_3_W/read, Cast_3)]]

df.ix[df.index.get_level_values('Period') != 0, 'Value'] = 0

NameError: name 'r_' is not defined

masking부터 진행ㅎ

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True], dtype=bool)

4519200

1

ValueError: labels ['U9'] not contained in axis

Question을 index로 가질 경우, 사람들이 다 다른 경우를 제시할 수

In [ ]:
user_in = Input(shape=(1,), dtype='int64', name='user_in')
u = Embedding(n_users, n_factors, input_length=1, W_regularizer=l2(1e-4))(user_in)
movie_in = Input(shape=(1,), dtype='int64', name='movie_in')
m = Embedding(n_movies, n_factors, input_length=1, W_regularizer=l2(1e-4))(movie_in)

In [ ]:
x = merge([u, m], mode='dot')
x = Flatten()(x)
model = Model([user_in, movie_in], x)
model.compile(Adam(0.001), loss='mse')

In [ ]:
model.fit([trn.userId, trn.movieId], trn.rating, batch_size=64, nb_epoch=1, 
          validation_data=([val.userId, val.movieId], val.rating))

In [ ]:
model.optimizer.lr=0.01

In [ ]:
model.fit([trn.userId, trn.movieId], trn.rating, batch_size=64, nb_epoch=3, 
          validation_data=([val.userId, val.movieId], val.rating))

In [ ]:
model.optimizer.lr=0.001

In [ ]:
model.fit([trn.userId, trn.movieId], trn.rating, batch_size=64, nb_epoch=3, 
          validation_data=([val.userId, val.movieId], val.rating))

# Learn With Simple Regressions

# Learn With Embeddings

In [ ]:
batch_size=100

# 상관 관계 분석

# 주성분 분석

# 시각화